UNICODE_ENABLE = no
# LEDs
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGBLIGHT_ANIMATIONS = no
LED_MIRRORED = no
WS2812_DRIVER = vendor
RGBLIGHT_FULL_POWER = no

SERIAL_DRIVER = vendor